"use client"

import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import Link from "next/link"
import { signInWithEmailAndPassword, signInWithCustomToken } from "firebase/auth"
import { auth } from "@/lib/firebase"
import { useRouter } from "next/navigation"
import { useState } from "react"
import { Building, User } from "lucide-react"

export default function LoginPage() {
  const [role, setRole] = useState<'admin' | 'staff'>('staff')
  const [email, setEmail] = useState("")
  const [password, setPassword] = useState("")
  const [error, setError] = useState("")
  const [isLoading, setIsLoading] = useState(false)
  const router = useRouter()

  const handleLogin = async (e: React.FormEvent) => {
    e.preventDefault()
    setIsLoading(true)
    setError("")

    try {
      if (role === 'admin') {
        // Admin hardcoded login
        const res = await fetch('/api/auth/admin', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ email, password })
        })
        
        let data: any = {}
        const contentType = res.headers.get("content-type")
        if (contentType && contentType.includes("application/json")) {
          data = await res.json()
        } else if (!res.ok) {
          throw new Error(`Server error (${res.status}): Make sure Firebase environment variables are set in Vercel.`)
        } else {
          throw new Error("Unexpected response from server.")
        }
        
        if (!res.ok) throw new Error(data.error || "Admin authentication failed")
        
        // Sign in with the custom token generated by the server
        await signInWithCustomToken(auth, data.token)
        router.push("/dashboard")
      } else {
        // Staff normal Firebase auth
        await signInWithEmailAndPassword(auth, email, password)
        router.push("/dashboard")
      }
    } catch (err: any) {
      setError(err.message || "Invalid credentials.")
    } finally {
      setIsLoading(false)
    }
  }

  return (
    <>
      <div className="text-center mb-8">
        <div className="inline-flex items-center gap-3 mb-6">
          <svg width="40" height="40" viewBox="0 0 40 40" fill="none" xmlns="http://www.w3.org/2000/svg">
            <rect width="40" height="40" rx="12" fill="#8A4FFF"/>
            <path d="M12 28C12 28 16 12 28 12" stroke="white" strokeWidth="4" strokeLinecap="round"/>
            <circle cx="28" cy="28" r="4" fill="white"/>
            <circle cx="12" cy="12" r="4" fill="white"/>
          </svg>
          <span className="text-4xl font-extrabold tracking-tight text-gray-900 dark:text-gray-100" style={{ fontFamily: 'var(--font-nunito)' }}>Rolled</span>
        </div>
        <h1 className="text-2xl font-bold text-gray-900 dark:text-gray-100 tracking-tight">Welcome back</h1>
        <p className="text-gray-500 dark:text-gray-400 mt-2">Log in to your account to continue</p>
      </div>

      <Card className="glass-card">
        <CardHeader className="space-y-1 pb-4">
          <div className="flex bg-gray-50 dark:bg-white/5 p-1 rounded-xl mb-4 border border-gray-200 dark:border-white/10">
            <button 
              onClick={() => setRole('staff')}
              className={`flex-1 py-2 text-sm font-semibold rounded-lg transition-colors flex items-center justify-center gap-2 ${role === 'staff' ? 'bg-white dark:bg-white/10 text-primary shadow-sm' : 'text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-100'}`}
            >
              <User size={16} /> Staff Login
            </button>
            <button 
              onClick={() => setRole('admin')}
              className={`flex-1 py-2 text-sm font-semibold rounded-lg transition-colors flex items-center justify-center gap-2 ${role === 'admin' ? 'bg-white dark:bg-white/10 text-primary shadow-sm' : 'text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-100'}`}
            >
              <Building size={16} /> Admin Login
            </button>
          </div>
          <CardTitle className="text-xl">{role === 'admin' ? "Admin Portal" : "Employee Portal"}</CardTitle>
          <CardDescription>
            {role === 'admin' ? "Enter your master credentials" : "Enter the credentials provided by your HR"}
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-5">
          {error && <div className="p-3 mb-4 text-sm text-red-600 bg-red-50 rounded-xl">{error}</div>}
          
          <form onSubmit={handleLogin} className="space-y-4">
            <div className="space-y-2">
              <label className="text-sm font-semibold text-gray-900 dark:text-gray-100">Email address</label>
              <Input type="email" placeholder={role === 'admin' ? "admin@company.com" : "name@company.com"} required value={email} onChange={e => setEmail(e.target.value)} className="bg-gray-50 dark:bg-white/5 border-gray-200 dark:border-white/10 focus:bg-white dark:focus:bg-[#1a1a24]" />
            </div>
            <div className="space-y-2">
              <div className="flex items-center justify-between">
                <label className="text-sm font-semibold text-gray-900 dark:text-gray-100">Password</label>
                {role === 'staff' && (
                  <Link href="#" className="text-sm font-medium text-primary hover:text-primary-dark transition-colors">
                    Forgot password?
                  </Link>
                )}
              </div>
              <Input type="password" placeholder="••••••••" required value={password} onChange={e => setPassword(e.target.value)} className="bg-gray-50 dark:bg-white/5 border-gray-200 dark:border-white/10 focus:bg-white dark:focus:bg-[#1a1a24]" />
            </div>
            <Button type="submit" disabled={isLoading} className="w-full h-12 text-base rounded-xl mt-6">
              {isLoading ? "Signing in..." : "Sign in"}
            </Button>
          </form>
        </CardContent>
      </Card>
    </>
  )
}
